
package org.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserSOAP", targetNamespace = "http://soap/", wsdlLocation = "http://localhost:8080/Server/UserSOAP?wsdl")
public class UserSOAP_Service
    extends Service
{

    private final static URL USERSOAP_WSDL_LOCATION;
    private final static WebServiceException USERSOAP_EXCEPTION;
    private final static QName USERSOAP_QNAME = new QName("http://soap/", "UserSOAP");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Server/UserSOAP?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERSOAP_WSDL_LOCATION = url;
        USERSOAP_EXCEPTION = e;
    }

    public UserSOAP_Service() {
        super(__getWsdlLocation(), USERSOAP_QNAME);
    }

    public UserSOAP_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERSOAP_QNAME, features);
    }

    public UserSOAP_Service(URL wsdlLocation) {
        super(wsdlLocation, USERSOAP_QNAME);
    }

    public UserSOAP_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERSOAP_QNAME, features);
    }

    public UserSOAP_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserSOAP_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserSOAP
     */
    @WebEndpoint(name = "UserSOAPPort")
    public UserSOAP getUserSOAPPort() {
        return super.getPort(new QName("http://soap/", "UserSOAPPort"), UserSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserSOAP
     */
    @WebEndpoint(name = "UserSOAPPort")
    public UserSOAP getUserSOAPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap/", "UserSOAPPort"), UserSOAP.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERSOAP_EXCEPTION!= null) {
            throw USERSOAP_EXCEPTION;
        }
        return USERSOAP_WSDL_LOCATION;
    }

}
